# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('acc_type', models.CharField(choices=[('BK', 'Banco'), ('EX', 'Despesa'), ('IN', 'Recurso')], default='EX', max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acc_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taken', to='financial.Account')),
                ('acc_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added', to='financial.Account')),
            ],
        ),
    ]
