# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 21:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20160129_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('BK', 'Banco'), ('EX', 'Despesa'), ('IN', 'Recurso')], default='EX', max_length=2, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='saldo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome da conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='acc_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taken', to='financial.Account', verbose_name='conta debitada'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='acc_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added', to='financial.Account', verbose_name='conta creditada'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=200, verbose_name='descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='valor'),
        ),
    ]
